-- Rounds — diagnosis vocabulary (366 rows). Run FIRST: cases reference these slugs.

insert into public.diagnoses (slug, canonical_name, alternative_names, category) values
    ('myocardial-infarction', 'Myocardial Infarction', array['MI', 'Heart Attack', 'Acute MI', 'STEMI', 'NSTEMI']::text[], 'Cardiology'),
    ('aortic-dissection', 'Aortic Dissection', array['Dissecting Aortic Aneurysm']::text[], 'Cardiology'),
    ('acute-pericarditis', 'Acute Pericarditis', array['Pericarditis']::text[], 'Cardiology'),
    ('infective-endocarditis', 'Infective Endocarditis', array['IE', 'Bacterial Endocarditis', 'Endocarditis']::text[], 'Cardiology'),
    ('wpw-syndrome', 'Wolff-Parkinson-White Syndrome', array['WPW', 'WPW Syndrome', 'Wolff Parkinson White']::text[], 'Cardiology'),
    ('hypertrophic-cardiomyopathy', 'Hypertrophic Cardiomyopathy', array['HCM', 'HOCM', 'Hypertrophic Obstructive Cardiomyopathy']::text[], 'Cardiology'),
    ('atrial-fibrillation', 'Atrial Fibrillation', array['AFib', 'AF', 'A-Fib']::text[], 'Cardiology'),
    ('acute-rheumatic-fever', 'Acute Rheumatic Fever', array['Rheumatic Fever', 'ARF']::text[], 'Cardiology'),
    ('cardiac-tamponade', 'Cardiac Tamponade', array['Tamponade', 'Pericardial Tamponade']::text[], 'Cardiology'),
    ('dilated-cardiomyopathy', 'Dilated Cardiomyopathy', array['DCM']::text[], 'Cardiology'),
    ('mitral-regurgitation', 'Mitral Regurgitation', array['MR', 'Mitral Insufficiency']::text[], 'Cardiology'),
    ('aortic-stenosis', 'Aortic Stenosis', array['AS']::text[], 'Cardiology'),
    ('ventricular-septal-defect', 'Ventricular Septal Defect', array['VSD']::text[], 'Cardiology'),
    ('coarctation-of-aorta', 'Coarctation of the Aorta', array['Aortic Coarctation', 'CoA']::text[], 'Cardiology'),
    ('tetralogy-of-fallot', 'Tetralogy of Fallot', array['TOF', 'Tet Spell', 'Tetralogy of Fallot - Tet Spell']::text[], 'Cardiology'),
    ('restrictive-cardiomyopathy', 'Restrictive Cardiomyopathy', array['RCM']::text[], 'Cardiology'),
    ('takotsubo-cardiomyopathy', 'Takotsubo Cardiomyopathy', array['Broken Heart Syndrome', 'Stress Cardiomyopathy']::text[], 'Cardiology'),
    ('mitral-stenosis', 'Mitral Stenosis', array['MS']::text[], 'Cardiology'),
    ('aortic-regurgitation', 'Aortic Regurgitation', array['AR', 'Aortic Insufficiency']::text[], 'Cardiology'),
    ('atrial-septal-defect', 'Atrial Septal Defect', array['ASD']::text[], 'Cardiology'),
    ('patent-ductus-arteriosus', 'Patent Ductus Arteriosus', array['PDA']::text[], 'Cardiology'),
    ('dressler-syndrome', 'Dressler Syndrome', array['Post-MI Pericarditis', 'Postmyocardial Infarction Syndrome']::text[], 'Cardiology'),
    ('myocarditis', 'Myocarditis', array['Viral Myocarditis']::text[], 'Cardiology'),
    ('pulmonary-hypertension', 'Pulmonary Hypertension', array['PH', 'PAH', 'Pulmonary Arterial Hypertension']::text[], 'Cardiology'),
    ('tricuspid-regurgitation', 'Tricuspid Regurgitation', array['TR']::text[], 'Cardiology'),
    ('pulmonic-stenosis', 'Pulmonic Stenosis', array['PS', 'Pulmonary Stenosis']::text[], 'Cardiology'),
    ('brugada-syndrome', 'Brugada Syndrome', array['Brugada']::text[], 'Cardiology'),
    ('long-qt-syndrome', 'Long QT Syndrome', array['LQTS']::text[], 'Cardiology'),
    ('transposition-great-arteries', 'Transposition of Great Arteries', array['TGA', 'D-TGA']::text[], 'Cardiology'),
    ('eisenmenger-syndrome', 'Eisenmenger Syndrome', array['Eisenmenger']::text[], 'Cardiology'),
    ('sick-sinus-syndrome', 'Sick Sinus Syndrome', array['SSS', 'Sinus Node Dysfunction']::text[], 'Cardiology'),
    ('patent-foramen-ovale', 'Patent Foramen Ovale', array['PFO']::text[], 'Cardiology'),
    ('multiple-sclerosis', 'Multiple Sclerosis', array['MS']::text[], 'Neurology'),
    ('subarachnoid-hemorrhage', 'Subarachnoid Hemorrhage', array['SAH']::text[], 'Neurology'),
    ('myasthenia-gravis', 'Myasthenia Gravis', array['MG']::text[], 'Neurology'),
    ('guillain-barre-syndrome', 'Guillain-Barre Syndrome', array['GBS', 'Guillain Barre', 'Guillain-Barre']::text[], 'Neurology'),
    ('parkinson-disease', 'Parkinson Disease', array['PD', 'Parkinson''s Disease', 'Parkinsons']::text[], 'Neurology'),
    ('alzheimer-disease', 'Alzheimer Disease', array['AD', 'Alzheimer''s Disease', 'Alzheimers']::text[], 'Neurology'),
    ('ischemic-stroke', 'Ischemic Stroke', array['Stroke', 'CVA', 'Cerebrovascular Accident']::text[], 'Neurology'),
    ('migraine', 'Migraine', array['Migraine Headache']::text[], 'Neurology'),
    ('seizure-disorder', 'Seizure Disorder', array['Epilepsy', 'Seizures']::text[], 'Neurology'),
    ('huntington-disease', 'Huntington Disease', array['HD', 'Huntington''s Disease', 'Huntingtons']::text[], 'Neurology'),
    ('bells-palsy', 'Bell''s Palsy', array['Bells Palsy', 'Bell Palsy']::text[], 'Neurology'),
    ('als', 'Amyotrophic Lateral Sclerosis', array['ALS', 'Lou Gehrig Disease', 'Lou Gehrig''s Disease']::text[], 'Neurology'),
    ('pseudotumor-cerebri', 'Pseudotumor Cerebri', array['Idiopathic Intracranial Hypertension', 'IIH']::text[], 'Neurology'),
    ('normal-pressure-hydrocephalus', 'Normal Pressure Hydrocephalus', array['NPH']::text[], 'Neurology'),
    ('wernicke-encephalopathy', 'Wernicke Encephalopathy', array['Wernicke''s Encephalopathy', 'Wernicke-Korsakoff']::text[], 'Neurology'),
    ('central-pontine-myelinolysis', 'Central Pontine Myelinolysis', array['CPM', 'Osmotic Demyelination Syndrome']::text[], 'Neurology'),
    ('trigeminal-neuralgia', 'Trigeminal Neuralgia', array['Tic Douloureux']::text[], 'Neurology'),
    ('creutzfeldt-jakob-disease', 'Creutzfeldt-Jakob Disease', array['CJD', 'Creutzfeldt Jakob']::text[], 'Neurology')
on conflict (slug) do update set
    canonical_name    = excluded.canonical_name,
    alternative_names = excluded.alternative_names,
    category          = excluded.category,
    updated_at        = now();

insert into public.diagnoses (slug, canonical_name, alternative_names, category) values
    ('friedreich-ataxia', 'Friedreich Ataxia', array['Friedreich''s Ataxia']::text[], 'Neurology'),
    ('charcot-marie-tooth', 'Charcot-Marie-Tooth Disease', array['CMT']::text[], 'Neurology'),
    ('syringomyelia', 'Syringomyelia', array['Syrinx']::text[], 'Neurology'),
    ('chiari-malformation', 'Posterior Fossa Malformations - Chiari', array['Chiari Malformation', 'Arnold-Chiari']::text[], 'Neurology'),
    ('lambert-eaton', 'Lambert-Eaton Myasthenic Syndrome', array['LEMS', 'Lambert Eaton']::text[], 'Neurology'),
    ('vertebrobasilar-insufficiency', 'Vertebrobasilar Insufficiency', array['VBI']::text[], 'Neurology'),
    ('cavernous-sinus-thrombosis', 'Cavernous Sinus Thrombosis', array['CST']::text[], 'Neurology'),
    ('subdural-hematoma', 'Subdural Hematoma', array['SDH']::text[], 'Neurology'),
    ('epidural-hematoma', 'Epidural Hematoma', array['EDH']::text[], 'Neurology'),
    ('tia', 'Transient Ischemic Attack', array['TIA', 'Mini Stroke']::text[], 'Neurology'),
    ('essential-tremor', 'Benign Essential Tremor', array['Essential Tremor']::text[], 'Neurology'),
    ('neurofibromatosis-1', 'Neurofibromatosis Type 1', array['NF1', 'Von Recklinghausen Disease']::text[], 'Neurology'),
    ('tuberous-sclerosis', 'Tuberous Sclerosis', array['TSC']::text[], 'Neurology'),
    ('glioblastoma', 'Glioblastoma Multiforme', array['GBM', 'Grade IV Astrocytoma', 'Glioblastoma']::text[], 'Neurology'),
    ('pulmonary-embolism', 'Pulmonary Embolism', array['PE']::text[], 'Pulmonology'),
    ('sarcoidosis', 'Sarcoidosis', array['Sarcoid']::text[], 'Pulmonology'),
    ('asthma-exacerbation', 'Asthma Exacerbation', array['Asthma Attack', 'Acute Asthma']::text[], 'Pulmonology'),
    ('pneumothorax', 'Pneumothorax', array['Collapsed Lung']::text[], 'Pulmonology'),
    ('tension-pneumothorax', 'Tension Pneumothorax', '{}'::text[], 'Pulmonology'),
    ('copd', 'Chronic Obstructive Pulmonary Disease', array['COPD', 'Emphysema', 'Chronic Bronchitis']::text[], 'Pulmonology'),
    ('cystic-fibrosis', 'Cystic Fibrosis', array['CF']::text[], 'Pulmonology'),
    ('idiopathic-pulmonary-fibrosis', 'Idiopathic Pulmonary Fibrosis', array['IPF']::text[], 'Pulmonology'),
    ('community-acquired-pneumonia', 'Community-Acquired Pneumonia', array['CAP', 'Pneumonia']::text[], 'Pulmonology'),
    ('sleep-apnea', 'Sleep Apnea', array['OSA', 'Obstructive Sleep Apnea']::text[], 'Pulmonology'),
    ('lung-adenocarcinoma', 'Lung Adenocarcinoma', array['Lung Cancer', 'NSCLC']::text[], 'Pulmonology'),
    ('alpha-1-antitrypsin-deficiency', 'Alpha-1 Antitrypsin Deficiency', array['A1AT Deficiency', 'Alpha-1']::text[], 'Pulmonology'),
    ('aspiration-pneumonia', 'Aspiration Pneumonia', '{}'::text[], 'Pulmonology'),
    ('bronchiectasis', 'Bronchiectasis', '{}'::text[], 'Pulmonology'),
    ('hypersensitivity-pneumonitis', 'Hypersensitivity Pneumonitis', array['HP', 'Extrinsic Allergic Alveolitis']::text[], 'Pulmonology'),
    ('ards', 'Acute Respiratory Distress Syndrome', array['ARDS']::text[], 'Pulmonology'),
    ('silicosis', 'Silicosis', '{}'::text[], 'Pulmonology'),
    ('asbestosis', 'Asbestosis', '{}'::text[], 'Pulmonology'),
    ('small-cell-lung-cancer', 'Small Cell Lung Cancer', array['SCLC']::text[], 'Pulmonology'),
    ('mesothelioma', 'Mesothelioma', array['Malignant Mesothelioma']::text[], 'Pulmonology'),
    ('pancoast-tumor', 'Pancoast Tumor', array['Superior Sulcus Tumor']::text[], 'Pulmonology'),
    ('granulomatosis-with-polyangiitis', 'Granulomatosis with Polyangiitis', array['Wegener Granulomatosis', 'Wegener''s Granulomatosis', 'GPA']::text[], 'Pulmonology'),
    ('churg-strauss-syndrome', 'Churg-Strauss Syndrome', array['Eosinophilic Granulomatosis with Polyangiitis', 'EGPA', 'Churg Strauss Syndrome']::text[], 'Pulmonology'),
    ('kartagener-syndrome', 'Kartagener Syndrome', array['Primary Ciliary Dyskinesia', 'Kartagener Syndrome Ciliary Defect']::text[], 'Pulmonology'),
    ('hamartoma', 'Hamartoma', array['Pulmonary Hamartoma']::text[], 'Pulmonology'),
    ('loeffler-syndrome', 'Loeffler Syndrome', array['Loffler Syndrome', 'Simple Pulmonary Eosinophilia']::text[], 'Pulmonology'),
    ('crohns-disease', 'Crohn''s Disease', array['Crohn Disease', 'Crohns', 'Regional Enteritis']::text[], 'Gastroenterology'),
    ('ulcerative-colitis', 'Ulcerative Colitis', array['UC']::text[], 'Gastroenterology'),
    ('appendicitis', 'Appendicitis', array['Acute Appendicitis']::text[], 'Gastroenterology'),
    ('celiac-disease', 'Celiac Disease', array['Celiac Sprue', 'Gluten Enteropathy']::text[], 'Gastroenterology'),
    ('acute-cholecystitis', 'Acute Cholecystitis', array['Cholecystitis']::text[], 'Gastroenterology'),
    ('hepatic-encephalopathy', 'Hepatic Encephalopathy', array['HE']::text[], 'Gastroenterology'),
    ('peptic-ulcer-disease', 'Peptic Ulcer Disease', array['PUD', 'Gastric Ulcer', 'Duodenal Ulcer']::text[], 'Gastroenterology'),
    ('esophageal-varices', 'Esophageal Varices', array['Varices']::text[], 'Gastroenterology'),
    ('diverticulitis', 'Diverticulitis', array['Acute Diverticulitis']::text[], 'Gastroenterology'),
    ('primary-sclerosing-cholangitis', 'Primary Sclerosing Cholangitis', array['PSC']::text[], 'Gastroenterology')
on conflict (slug) do update set
    canonical_name    = excluded.canonical_name,
    alternative_names = excluded.alternative_names,
    category          = excluded.category,
    updated_at        = now();

insert into public.diagnoses (slug, canonical_name, alternative_names, category) values
    ('alcoholic-hepatitis', 'Alcoholic Hepatitis', '{}'::text[], 'Gastroenterology'),
    ('acute-pancreatitis', 'Acute Pancreatitis', array['Pancreatitis']::text[], 'Gastroenterology'),
    ('achalasia', 'Achalasia', '{}'::text[], 'Gastroenterology'),
    ('mallory-weiss-tear', 'Mallory-Weiss Tear', array['Mallory Weiss Syndrome']::text[], 'Gastroenterology'),
    ('zenker-diverticulum', 'Zenker Diverticulum', array['Zenker''s Diverticulum', 'Pharyngeal Pouch']::text[], 'Gastroenterology'),
    ('barrett-esophagus', 'Barrett Esophagus', array['Barrett''s Esophagus']::text[], 'Gastroenterology'),
    ('primary-biliary-cholangitis', 'Primary Biliary Cholangitis', array['PBC', 'Primary Biliary Cirrhosis']::text[], 'Gastroenterology'),
    ('whipple-disease', 'Whipple Disease', array['Whipple''s Disease']::text[], 'Gastroenterology'),
    ('hemochromatosis', 'Hemochromatosis', array['Iron Overload', 'Hereditary Hemochromatosis']::text[], 'Gastroenterology'),
    ('wilson-disease', 'Wilson Disease', array['Wilson''s Disease', 'Hepatolenticular Degeneration']::text[], 'Gastroenterology'),
    ('budd-chiari-syndrome', 'Budd-Chiari Syndrome', array['Budd Chiari', 'Hepatic Vein Thrombosis']::text[], 'Gastroenterology'),
    ('spontaneous-bacterial-peritonitis', 'Spontaneous Bacterial Peritonitis', array['SBP']::text[], 'Gastroenterology'),
    ('peutz-jeghers-syndrome', 'Peutz-Jeghers Syndrome', array['PJS']::text[], 'Gastroenterology'),
    ('familial-adenomatous-polyposis', 'Familial Adenomatous Polyposis', array['FAP']::text[], 'Gastroenterology'),
    ('lynch-syndrome', 'Lynch Syndrome', array['HNPCC', 'Hereditary Nonpolyposis Colorectal Cancer']::text[], 'Gastroenterology'),
    ('ogilvie-syndrome', 'Ogilvie Syndrome', array['Acute Colonic Pseudo-obstruction']::text[], 'Gastroenterology'),
    ('tropical-sprue', 'Tropical Sprue', '{}'::text[], 'Gastroenterology'),
    ('ischemic-colitis', 'Ischemic Colitis', '{}'::text[], 'Gastroenterology'),
    ('carcinoid-tumor', 'Carcinoid Tumor', array['Carcinoid']::text[], 'Gastroenterology'),
    ('mesenteric-ischemia', 'Mesenteric Ischemia', array['Acute Mesenteric Ischemia']::text[], 'Gastroenterology'),
    ('pseudomembranous-colitis', 'Pseudomembranous Colitis', array['C. diff Colitis']::text[], 'Gastroenterology'),
    ('clostridium-difficile-colitis', 'Clostridium difficile Colitis', array['C. diff', 'CDI', 'C difficile Infection']::text[], 'Gastroenterology'),
    ('meckel-diverticulum', 'Meckel Diverticulum', array['Meckel''s Diverticulum']::text[], 'Gastroenterology'),
    ('gardner-syndrome', 'Gardner Syndrome', array['FAP with Extra-intestinal Manifestations']::text[], 'Gastroenterology'),
    ('acute-kidney-injury', 'Acute Kidney Injury', array['AKI', 'Acute Renal Failure', 'ARF']::text[], 'Nephrology'),
    ('nephrotic-syndrome', 'Nephrotic Syndrome', '{}'::text[], 'Nephrology'),
    ('iga-nephropathy', 'IgA Nephropathy', array['Berger Disease', 'Berger''s Disease']::text[], 'Nephrology'),
    ('acute-tubular-necrosis', 'Acute Tubular Necrosis', array['ATN']::text[], 'Nephrology'),
    ('polycystic-kidney-disease', 'Polycystic Kidney Disease', array['PKD', 'ADPKD', 'Polycystic Kidney Disease (ADPKD)', 'Adult Polycystic Kidney Disease', 'Adult PKD']::text[], 'Nephrology'),
    ('goodpasture-syndrome', 'Goodpasture Syndrome', array['Anti-GBM Disease', 'Goodpasture''s Syndrome']::text[], 'Nephrology'),
    ('acute-interstitial-nephritis', 'Acute Interstitial Nephritis', array['AIN']::text[], 'Nephrology'),
    ('renal-artery-stenosis', 'Renal Artery Stenosis', array['RAS']::text[], 'Nephrology'),
    ('nephrolithiasis', 'Nephrolithiasis', array['Kidney Stones', 'Renal Calculi']::text[], 'Nephrology'),
    ('membranous-nephropathy', 'Membranous Nephropathy', array['Membranous Glomerulonephritis']::text[], 'Nephrology'),
    ('hemolytic-uremic-syndrome', 'Hemolytic Uremic Syndrome', array['HUS']::text[], 'Nephrology'),
    ('alport-syndrome', 'Alport Syndrome', '{}'::text[], 'Nephrology'),
    ('fanconi-syndrome', 'Fanconi Syndrome', '{}'::text[], 'Nephrology'),
    ('bartter-syndrome', 'Bartter Syndrome', '{}'::text[], 'Nephrology'),
    ('gitelman-syndrome', 'Gitelman Syndrome', '{}'::text[], 'Nephrology'),
    ('focal-segmental-glomerulosclerosis', 'Focal Segmental Glomerulosclerosis', array['FSGS']::text[], 'Nephrology'),
    ('psgn', 'Poststreptococcal Glomerulonephritis', array['PSGN', 'Post-Streptococcal Glomerulonephritis', 'Post Streptococcal Glomerulonephritis']::text[], 'Nephrology'),
    ('liddle-syndrome', 'Liddle Syndrome', array['Pseudohyperaldosteronism']::text[], 'Nephrology'),
    ('rpgn', 'Rapidly Progressive Glomerulonephritis', array['RPGN', 'Crescentic Glomerulonephritis']::text[], 'Nephrology'),
    ('diabetic-nephropathy', 'Diabetic Nephropathy', array['Diabetic Kidney Disease']::text[], 'Nephrology'),
    ('hypertensive-nephropathy', 'Hypertensive Nephropathy', array['Hypertensive Kidney Disease']::text[], 'Nephrology'),
    ('contrast-induced-nephropathy', 'Contrast-Induced Nephropathy', array['CIN', 'Contrast Nephropathy']::text[], 'Nephrology'),
    ('rhabdomyolysis', 'Rhabdomyolysis', '{}'::text[], 'Nephrology'),
    ('tumor-lysis-syndrome', 'Tumor Lysis Syndrome', array['TLS']::text[], 'Nephrology'),
    ('medullary-sponge-kidney', 'Medullary Sponge Kidney', '{}'::text[], 'Nephrology'),
    ('minimal-change-disease', 'Minimal Change Disease', array['MCD', 'Nil Disease']::text[], 'Nephrology')
on conflict (slug) do update set
    canonical_name    = excluded.canonical_name,
    alternative_names = excluded.alternative_names,
    category          = excluded.category,
    updated_at        = now();

insert into public.diagnoses (slug, canonical_name, alternative_names, category) values
    ('diabetic-ketoacidosis', 'Diabetic Ketoacidosis', array['DKA']::text[], 'Endocrinology'),
    ('graves-disease', 'Graves Disease', array['Graves'' Disease', 'Basedow Disease', 'Hyperthyroidism', 'Thyrotoxicosis', 'Toxic Diffuse Goiter']::text[], 'Endocrinology'),
    ('hashimoto-thyroiditis', 'Hashimoto Thyroiditis', array['Hashimoto''s Thyroiditis', 'Chronic Lymphocytic Thyroiditis']::text[], 'Endocrinology'),
    ('cushing-syndrome', 'Cushing Syndrome', array['Cushing''s Syndrome', 'Hypercortisolism']::text[], 'Endocrinology'),
    ('addison-disease', 'Addison Disease', array['Addison''s Disease', 'Primary Adrenal Insufficiency']::text[], 'Endocrinology'),
    ('hypothyroidism', 'Hypothyroidism', array['Underactive Thyroid']::text[], 'Endocrinology'),
    ('diabetes-insipidus', 'Diabetes Insipidus', array['DI', 'Central Diabetes Insipidus', 'Diabetes Insipidus (Central)', 'Neurogenic DI']::text[], 'Endocrinology'),
    ('siadh', 'SIADH', array['Syndrome of Inappropriate ADH', 'Syndrome of Inappropriate Antidiuretic Hormone']::text[], 'Endocrinology'),
    ('pheochromocytoma', 'Pheochromocytoma', array['Pheo']::text[], 'Endocrinology'),
    ('hyperparathyroidism', 'Hyperparathyroidism', array['Primary Hyperparathyroidism']::text[], 'Endocrinology'),
    ('acromegaly', 'Acromegaly', '{}'::text[], 'Endocrinology'),
    ('type-2-diabetes', 'Type 2 Diabetes Mellitus', array['T2DM', 'Type 2 Diabetes', 'Diabetes Mellitus']::text[], 'Endocrinology'),
    ('conn-syndrome', 'Conn Syndrome', array['Primary Hyperaldosteronism']::text[], 'Endocrinology'),
    ('secondary-hyperaldosteronism', 'Hyperaldosteronism Secondary', array['Secondary Hyperaldosteronism']::text[], 'Endocrinology'),
    ('carcinoid-syndrome', 'Carcinoid Syndrome', '{}'::text[], 'Endocrinology'),
    ('zollinger-ellison-syndrome', 'Zollinger-Ellison Syndrome', array['ZES', 'Gastrinoma']::text[], 'Endocrinology'),
    ('men-1', 'Multiple Endocrine Neoplasia Type 1', array['MEN1', 'MEN 1']::text[], 'Endocrinology'),
    ('men-2', 'Multiple Endocrine Neoplasia Type 2', array['MEN2', 'MEN 2']::text[], 'Endocrinology'),
    ('sheehan-syndrome', 'Sheehan Syndrome', array['Postpartum Hypopituitarism']::text[], 'Endocrinology'),
    ('craniopharyngioma', 'Craniopharyngioma', '{}'::text[], 'Endocrinology'),
    ('insulinoma', 'Insulinoma', '{}'::text[], 'Endocrinology'),
    ('glucagonoma', 'Glucagonoma', '{}'::text[], 'Endocrinology'),
    ('vipoma', 'VIPoma', array['Verner-Morrison Syndrome', 'WDHA Syndrome']::text[], 'Endocrinology'),
    ('congenital-adrenal-hyperplasia', 'Congenital Adrenal Hyperplasia', array['CAH']::text[], 'Endocrinology'),
    ('klinefelter-syndrome', 'Klinefelter Syndrome', array['47 XXY', 'XXY']::text[], 'Endocrinology'),
    ('turner-syndrome', 'Turner Syndrome', array['45 XO', 'XO']::text[], 'Endocrinology'),
    ('prolactinoma', 'Prolactinoma', '{}'::text[], 'Endocrinology'),
    ('congenital-hypothyroidism', 'Congenital Hypothyroidism', array['Cretinism']::text[], 'Endocrinology'),
    ('systemic-lupus-erythematosus', 'Systemic Lupus Erythematosus', array['SLE', 'Lupus']::text[], 'Rheumatology'),
    ('giant-cell-arteritis', 'Giant Cell Arteritis', array['Temporal Arteritis', 'GCA', 'Cranial Arteritis']::text[], 'Rheumatology'),
    ('ankylosing-spondylitis', 'Ankylosing Spondylitis', array['AS']::text[], 'Rheumatology'),
    ('gout', 'Gout', array['Gouty Arthritis']::text[], 'Rheumatology'),
    ('rheumatoid-arthritis', 'Rheumatoid Arthritis', array['RA']::text[], 'Rheumatology'),
    ('osteoarthritis', 'Osteoarthritis', array['OA', 'Degenerative Joint Disease']::text[], 'Rheumatology'),
    ('pseudogout', 'Pseudogout', array['CPPD', 'Calcium Pyrophosphate Deposition Disease']::text[], 'Rheumatology'),
    ('reactive-arthritis', 'Reactive Arthritis', array['Reiter Syndrome']::text[], 'Rheumatology'),
    ('sjogren-syndrome', 'Sjogren Syndrome', array['Sjögren Syndrome', 'Sjogren''s Syndrome', 'Sjögren''s Syndrome', 'Sicca Syndrome', 'Sjogren''s']::text[], 'Rheumatology'),
    ('polymyalgia-rheumatica', 'Polymyalgia Rheumatica', array['PMR']::text[], 'Rheumatology'),
    ('systemic-sclerosis', 'Scleroderma', array['Systemic Sclerosis', 'Scleroderma (Diffuse)', 'Diffuse Scleroderma', 'SSc']::text[], 'Rheumatology'),
    ('dermatomyositis', 'Dermatomyositis', array['DM']::text[], 'Rheumatology'),
    ('behcet-disease', 'Behcet Disease', array['Behçet Disease', 'Behcet''s Disease']::text[], 'Rheumatology'),
    ('mixed-connective-tissue-disease', 'Mixed Connective Tissue Disease', array['MCTD']::text[], 'Rheumatology'),
    ('takayasu-arteritis', 'Takayasu Arteritis', array['Pulseless Disease']::text[], 'Rheumatology'),
    ('polyarteritis-nodosa', 'Polyarteritis Nodosa', array['PAN']::text[], 'Rheumatology'),
    ('relapsing-polychondritis', 'Relapsing Polychondritis', '{}'::text[], 'Rheumatology'),
    ('adult-onset-still-disease', 'Adult-Onset Still Disease', array['AOSD', 'Adult Still Disease']::text[], 'Rheumatology'),
    ('felty-syndrome', 'Felty Syndrome', '{}'::text[], 'Rheumatology'),
    ('henoch-schonlein-purpura', 'Henoch-Schonlein Purpura', array['HSP', 'IgA Vasculitis', 'Henoch-Schönlein Purpura']::text[], 'Rheumatology'),
    ('microscopic-polyangiitis', 'Microscopic Polyangiitis', array['MPA']::text[], 'Rheumatology'),
    ('cryoglobulinemia', 'Cryoglobulinemia', '{}'::text[], 'Rheumatology')
on conflict (slug) do update set
    canonical_name    = excluded.canonical_name,
    alternative_names = excluded.alternative_names,
    category          = excluded.category,
    updated_at        = now();

insert into public.diagnoses (slug, canonical_name, alternative_names, category) values
    ('antiphospholipid-syndrome', 'Antiphospholipid Syndrome', array['APS', 'APLS']::text[], 'Rheumatology'),
    ('septic-arthritis', 'Septic Arthritis', array['Infectious Arthritis']::text[], 'Rheumatology'),
    ('sickle-cell-crisis', 'Sickle Cell Crisis', array['Sickle Cell Disease', 'SCD', 'Vaso-occlusive Crisis']::text[], 'Hematology'),
    ('iron-deficiency-anemia', 'Iron Deficiency Anemia', array['IDA']::text[], 'Hematology'),
    ('apl', 'Acute Promyelocytic Leukemia', array['APL', 'M3 AML']::text[], 'Hematology'),
    ('itp', 'Immune Thrombocytopenic Purpura', array['ITP', 'Idiopathic Thrombocytopenic Purpura']::text[], 'Hematology'),
    ('vitamin-b12-deficiency', 'Vitamin B12 Deficiency', array['B12 Deficiency', 'Cobalamin Deficiency']::text[], 'Hematology'),
    ('aml', 'Acute Myeloid Leukemia', array['AML']::text[], 'Hematology'),
    ('all', 'Acute Lymphoblastic Leukemia', array['ALL']::text[], 'Hematology'),
    ('cml', 'Chronic Myeloid Leukemia', array['CML']::text[], 'Hematology'),
    ('hodgkin-lymphoma', 'Hodgkin Lymphoma', array['Hodgkin''s Lymphoma', 'Hodgkin Disease']::text[], 'Hematology'),
    ('non-hodgkin-lymphoma', 'Non-Hodgkin Lymphoma', array['NHL']::text[], 'Hematology'),
    ('hemophilia-a', 'Hemophilia A', array['Factor VIII Deficiency']::text[], 'Hematology'),
    ('von-willebrand-disease', 'Von Willebrand Disease', array['vWD']::text[], 'Hematology'),
    ('dic', 'Disseminated Intravascular Coagulation', array['DIC']::text[], 'Hematology'),
    ('thalassemia', 'Thalassemia', array['Beta Thalassemia', 'Alpha Thalassemia']::text[], 'Hematology'),
    ('g6pd-deficiency', 'Glucose-6-Phosphate Dehydrogenase Deficiency', array['G6PD Deficiency']::text[], 'Hematology'),
    ('hereditary-spherocytosis', 'Hereditary Spherocytosis', array['HS']::text[], 'Hematology'),
    ('pnh', 'Paroxysmal Nocturnal Hemoglobinuria', array['PNH']::text[], 'Hematology'),
    ('polycythemia-vera', 'Polycythemia Vera', array['PV']::text[], 'Hematology'),
    ('essential-thrombocythemia', 'Essential Thrombocythemia', array['ET']::text[], 'Hematology'),
    ('myelofibrosis', 'Myelofibrosis', array['Primary Myelofibrosis']::text[], 'Hematology'),
    ('multiple-myeloma', 'Multiple Myeloma', array['MM', 'Plasma Cell Myeloma']::text[], 'Hematology'),
    ('waldenstrom-macroglobulinemia', 'Waldenstrom Macroglobulinemia', array['WM', 'Waldenström Macroglobulinemia']::text[], 'Hematology'),
    ('ttp', 'Thrombotic Thrombocytopenic Purpura', array['TTP']::text[], 'Hematology'),
    ('aplastic-anemia', 'Aplastic Anemia', '{}'::text[], 'Hematology'),
    ('myelodysplastic-syndrome', 'Myelodysplastic Syndrome', array['MDS']::text[], 'Hematology'),
    ('hairy-cell-leukemia', 'Hairy Cell Leukemia', array['HCL']::text[], 'Hematology'),
    ('cll', 'Chronic Lymphocytic Leukemia', array['CLL']::text[], 'Hematology'),
    ('langerhans-cell-histiocytosis', 'Langerhans Cell Histiocytosis', array['LCH', 'Histiocytosis X']::text[], 'Hematology'),
    ('bernard-soulier-syndrome', 'Bernard-Soulier Syndrome', '{}'::text[], 'Hematology'),
    ('glanzmann-thrombasthenia', 'Glanzmann Thrombasthenia', '{}'::text[], 'Hematology'),
    ('factor-v-leiden', 'Factor V Leiden', array['FVL']::text[], 'Hematology'),
    ('pernicious-anemia', 'Pernicious Anemia', '{}'::text[], 'Hematology'),
    ('burkitt-lymphoma', 'Burkitt Lymphoma', array['Burkitt''s Lymphoma']::text[], 'Hematology'),
    ('bacterial-meningitis', 'Bacterial Meningitis', array['Meningitis']::text[], 'Infectious Disease'),
    ('tuberculosis', 'Tuberculosis', array['TB']::text[], 'Infectious Disease'),
    ('lyme-disease', 'Lyme Disease', array['Lyme Borreliosis']::text[], 'Infectious Disease'),
    ('rocky-mountain-spotted-fever', 'Rocky Mountain Spotted Fever', array['RMSF']::text[], 'Infectious Disease'),
    ('hiv-aids', 'HIV/AIDS', array['HIV', 'AIDS']::text[], 'Infectious Disease'),
    ('infectious-mononucleosis', 'Infectious Mononucleosis', array['Mono', 'EBV Infection']::text[], 'Infectious Disease'),
    ('toxic-shock-syndrome', 'Toxic Shock Syndrome', array['TSS']::text[], 'Infectious Disease'),
    ('candidiasis', 'Candidiasis', array['Candida Infection', 'Thrush']::text[], 'Infectious Disease'),
    ('pneumocystis-pneumonia', 'Pneumocystis Pneumonia', array['PCP', 'Pneumocystis Jirovecii Pneumonia', 'PJP']::text[], 'Infectious Disease'),
    ('malaria', 'Malaria', '{}'::text[], 'Infectious Disease'),
    ('toxoplasmosis', 'Toxoplasmosis', array['Toxoplasma Infection']::text[], 'Infectious Disease'),
    ('cryptococcal-meningitis', 'Cryptococcal Meningitis', array['Cryptococcosis']::text[], 'Infectious Disease'),
    ('histoplasmosis', 'Histoplasmosis', '{}'::text[], 'Infectious Disease'),
    ('coccidioidomycosis', 'Coccidioidomycosis', array['Valley Fever']::text[], 'Infectious Disease'),
    ('blastomycosis', 'Blastomycosis', '{}'::text[], 'Infectious Disease')
on conflict (slug) do update set
    canonical_name    = excluded.canonical_name,
    alternative_names = excluded.alternative_names,
    category          = excluded.category,
    updated_at        = now();

insert into public.diagnoses (slug, canonical_name, alternative_names, category) values
    ('actinomycosis', 'Actinomycosis', '{}'::text[], 'Infectious Disease'),
    ('nocardiosis', 'Nocardiosis', '{}'::text[], 'Infectious Disease'),
    ('cat-scratch-disease', 'Cat Scratch Disease', array['Bartonella Infection']::text[], 'Infectious Disease'),
    ('erythema-migrans', 'Erythema Migrans', '{}'::text[], 'Infectious Disease'),
    ('scarlet-fever', 'Scarlet Fever', array['Scarlatina']::text[], 'Infectious Disease'),
    ('roseola-infantum', 'Roseola Infantum', array['Sixth Disease', 'Exanthem Subitum']::text[], 'Infectious Disease'),
    ('hand-foot-mouth-disease', 'Hand-Foot-Mouth Disease', array['HFMD']::text[], 'Infectious Disease'),
    ('botulism', 'Botulism', '{}'::text[], 'Infectious Disease'),
    ('tetanus', 'Tetanus', array['Lockjaw']::text[], 'Infectious Disease'),
    ('major-depressive-disorder', 'Major Depressive Disorder', array['MDD', 'Depression', 'Major Depression']::text[], 'Psychiatry'),
    ('generalized-anxiety-disorder', 'Generalized Anxiety Disorder', array['GAD', 'Anxiety']::text[], 'Psychiatry'),
    ('schizophrenia', 'Schizophrenia', '{}'::text[], 'Psychiatry'),
    ('bipolar-disorder', 'Bipolar Disorder', array['Bipolar', 'Manic Depression']::text[], 'Psychiatry'),
    ('panic-disorder', 'Panic Disorder', array['Panic Attacks']::text[], 'Psychiatry'),
    ('anorexia-nervosa', 'Anorexia Nervosa', array['Anorexia']::text[], 'Psychiatry'),
    ('ocd', 'Obsessive-Compulsive Disorder', array['OCD']::text[], 'Psychiatry'),
    ('ptsd', 'Post-Traumatic Stress Disorder', array['PTSD']::text[], 'Psychiatry'),
    ('alcohol-withdrawal', 'Alcohol Withdrawal', array['Delirium Tremens', 'DTs']::text[], 'Psychiatry'),
    ('bulimia-nervosa', 'Bulimia Nervosa', array['Bulimia']::text[], 'Psychiatry'),
    ('adhd', 'Attention-Deficit Hyperactivity Disorder', array['ADHD', 'ADD']::text[], 'Psychiatry'),
    ('autism-spectrum-disorder', 'Autism Spectrum Disorder', array['ASD', 'Autism']::text[], 'Psychiatry'),
    ('neuroleptic-malignant-syndrome', 'Neuroleptic Malignant Syndrome', array['NMS']::text[], 'Psychiatry'),
    ('serotonin-syndrome', 'Serotonin Syndrome', '{}'::text[], 'Psychiatry'),
    ('somatization-disorder', 'Somatization Disorder', array['Somatic Symptom Disorder']::text[], 'Psychiatry'),
    ('conversion-disorder', 'Conversion Disorder', array['Functional Neurological Disorder']::text[], 'Psychiatry'),
    ('tourette-syndrome', 'Tourette Syndrome', array['Tourette''s Syndrome']::text[], 'Psychiatry'),
    ('psoriasis', 'Psoriasis', '{}'::text[], 'Dermatology'),
    ('melanoma', 'Melanoma', array['Malignant Melanoma']::text[], 'Dermatology'),
    ('basal-cell-carcinoma', 'Basal Cell Carcinoma', array['BCC']::text[], 'Dermatology'),
    ('eczema', 'Eczema', array['Atopic Dermatitis']::text[], 'Dermatology'),
    ('stevens-johnson-syndrome', 'Stevens-Johnson Syndrome', array['SJS', 'TEN', 'Toxic Epidermal Necrolysis']::text[], 'Dermatology'),
    ('squamous-cell-carcinoma', 'Squamous Cell Carcinoma', array['SCC']::text[], 'Dermatology'),
    ('pemphigus-vulgaris', 'Pemphigus Vulgaris', '{}'::text[], 'Dermatology'),
    ('bullous-pemphigoid', 'Bullous Pemphigoid', '{}'::text[], 'Dermatology'),
    ('erythema-multiforme', 'Erythema Multiforme', array['EM']::text[], 'Dermatology'),
    ('acanthosis-nigricans', 'Acanthosis Nigricans', '{}'::text[], 'Dermatology'),
    ('pityriasis-rosea', 'Pityriasis Rosea', '{}'::text[], 'Dermatology'),
    ('seborrheic-keratosis', 'Seborrheic Keratosis', '{}'::text[], 'Dermatology'),
    ('actinic-keratosis', 'Actinic Keratosis', array['Solar Keratosis']::text[], 'Dermatology'),
    ('dermatitis-herpetiformis', 'Dermatitis Herpetiformis', array['DH']::text[], 'Dermatology'),
    ('kawasaki-disease', 'Kawasaki Disease', array['Mucocutaneous Lymph Node Syndrome']::text[], 'Pediatrics'),
    ('croup', 'Croup', array['Laryngotracheobronchitis']::text[], 'Pediatrics'),
    ('epiglottitis', 'Epiglottitis', '{}'::text[], 'Pediatrics'),
    ('intussusception', 'Intussusception', '{}'::text[], 'Pediatrics'),
    ('pyloric-stenosis', 'Pyloric Stenosis', array['Hypertrophic Pyloric Stenosis', 'Hypertrophic Pyloric Stenosis - Late Presentation']::text[], 'Pediatrics'),
    ('respiratory-distress-syndrome', 'Respiratory Distress Syndrome', array['RDS', 'Hyaline Membrane Disease']::text[], 'Pediatrics'),
    ('neonatal-jaundice', 'Neonatal Jaundice', array['Physiologic Jaundice', 'Hyperbilirubinemia']::text[], 'Pediatrics'),
    ('hirschsprung-disease', 'Hirschsprung Disease', array['Congenital Megacolon']::text[], 'Pediatrics'),
    ('necrotizing-enterocolitis', 'Necrotizing Enterocolitis', array['NEC']::text[], 'Pediatrics'),
    ('retinopathy-of-prematurity', 'Retinopathy of Prematurity', array['ROP']::text[], 'Pediatrics')
on conflict (slug) do update set
    canonical_name    = excluded.canonical_name,
    alternative_names = excluded.alternative_names,
    category          = excluded.category,
    updated_at        = now();

insert into public.diagnoses (slug, canonical_name, alternative_names, category) values
    ('digeorge-syndrome', 'DiGeorge Syndrome', array['22q11.2 Deletion Syndrome', 'Velocardiofacial Syndrome']::text[], 'Pediatrics'),
    ('wiskott-aldrich-syndrome', 'Wiskott-Aldrich Syndrome', array['WAS']::text[], 'Pediatrics'),
    ('bronchiolitis', 'Bronchiolitis', array['RSV Bronchiolitis']::text[], 'Pediatrics'),
    ('kernicterus', 'Kernicterus', array['Bilirubin Encephalopathy']::text[], 'Pediatrics'),
    ('erb-palsy', 'Erb Palsy', array['Erb''s Palsy', 'Erb-Duchenne Palsy']::text[], 'Pediatrics'),
    ('tracheoesophageal-fistula', 'Tracheoesophageal Fistula', array['TEF', 'Esophageal Atresia']::text[], 'Pediatrics'),
    ('ectopic-pregnancy', 'Ectopic Pregnancy', array['Tubal Pregnancy']::text[], 'Obstetrics/Gynecology'),
    ('pcos', 'Polycystic Ovary Syndrome', array['PCOS']::text[], 'Obstetrics/Gynecology'),
    ('preeclampsia', 'Preeclampsia', array['Pre-eclampsia', 'Toxemia of Pregnancy']::text[], 'Obstetrics/Gynecology'),
    ('endometriosis', 'Endometriosis', '{}'::text[], 'Obstetrics/Gynecology'),
    ('placenta-previa', 'Placenta Previa', '{}'::text[], 'Obstetrics/Gynecology'),
    ('hellp-syndrome', 'HELLP Syndrome', '{}'::text[], 'Obstetrics/Gynecology'),
    ('placental-abruption', 'Placental Abruption', array['Abruptio Placentae']::text[], 'Obstetrics/Gynecology'),
    ('gestational-trophoblastic-disease', 'Gestational Trophoblastic Disease', array['Molar Pregnancy', 'Hydatidiform Mole']::text[], 'Obstetrics/Gynecology'),
    ('chorioamnionitis', 'Chorioamnionitis', array['Intra-amniotic Infection']::text[], 'Obstetrics/Gynecology'),
    ('testicular-torsion', 'Testicular Torsion', '{}'::text[], 'Urology'),
    ('bph', 'Benign Prostatic Hyperplasia', array['BPH', 'Enlarged Prostate']::text[], 'Urology'),
    ('prostate-cancer', 'Prostate Cancer', '{}'::text[], 'Urology'),
    ('testicular-seminoma', 'Testicular Seminoma', array['Seminoma']::text[], 'Urology'),
    ('testicular-nsgct', 'Testicular Non-Seminomatous Germ Cell Tumor', array['NSGCT']::text[], 'Urology'),
    ('epididymitis', 'Epididymitis', '{}'::text[], 'Urology'),
    ('varicocele', 'Varicocele', '{}'::text[], 'Urology'),
    ('hydrocele', 'Hydrocele', '{}'::text[], 'Urology'),
    ('osteomyelitis', 'Osteomyelitis', '{}'::text[], 'Orthopedics'),
    ('osgood-schlatter', 'Osgood-Schlatter Disease', array['Osgood Schlatter']::text[], 'Orthopedics'),
    ('scfe', 'Slipped Capital Femoral Epiphysis', array['SCFE']::text[], 'Orthopedics'),
    ('legg-calve-perthes', 'Legg-Calve-Perthes Disease', array['Legg Calve Perthes', 'Perthes Disease']::text[], 'Orthopedics'),
    ('developmental-dysplasia-hip', 'Developmental Dysplasia of the Hip', array['DDH', 'Hip Dysplasia']::text[], 'Orthopedics'),
    ('compartment-syndrome', 'Compartment Syndrome', '{}'::text[], 'Orthopedics'),
    ('osteosarcoma', 'Osteosarcoma', '{}'::text[], 'Orthopedics'),
    ('ewing-sarcoma', 'Ewing Sarcoma', array['Ewing''s Sarcoma']::text[], 'Orthopedics'),
    ('paget-disease-bone', 'Paget Disease of Bone', array['Paget''s Disease']::text[], 'Orthopedics'),
    ('glaucoma', 'Glaucoma', array['Open-Angle Glaucoma', 'Acute Angle-Closure Glaucoma']::text[], 'Ophthalmology'),
    ('cataract', 'Cataract', '{}'::text[], 'Ophthalmology'),
    ('retinal-detachment', 'Retinal Detachment', '{}'::text[], 'Ophthalmology'),
    ('macular-degeneration', 'Macular Degeneration', array['AMD', 'Age-Related Macular Degeneration']::text[], 'Ophthalmology'),
    ('diabetic-retinopathy', 'Diabetic Retinopathy', '{}'::text[], 'Ophthalmology'),
    ('central-retinal-artery-occlusion', 'Central Retinal Artery Occlusion', array['CRAO']::text[], 'Ophthalmology'),
    ('papilledema', 'Papilledema', '{}'::text[], 'Ophthalmology'),
    ('meniere-disease', 'Meniere Disease', array['Ménière Disease', 'Meniere''s Disease']::text[], 'ENT'),
    ('vestibular-schwannoma', 'Vestibular Schwannoma', array['Acoustic Neuroma']::text[], 'ENT'),
    ('acute-otitis-media', 'Acute Otitis Media', array['AOM', 'Ear Infection']::text[], 'ENT'),
    ('otitis-externa', 'Otitis Externa', array['Swimmer''s Ear']::text[], 'ENT'),
    ('acute-bacterial-sinusitis', 'Acute Bacterial Sinusitis', array['Sinusitis']::text[], 'ENT'),
    ('allergic-rhinitis', 'Allergic Rhinitis', array['Hay Fever']::text[], 'ENT'),
    ('dvt', 'Deep Vein Thrombosis', array['DVT']::text[], 'Vascular'),
    ('peripheral-arterial-disease', 'Peripheral Arterial Disease', array['PAD', 'Peripheral Vascular Disease']::text[], 'Vascular'),
    ('aaa', 'Abdominal Aortic Aneurysm', array['AAA']::text[], 'Vascular'),
    ('varicose-veins', 'Varicose Veins', '{}'::text[], 'Vascular'),
    ('phenylketonuria', 'Phenylketonuria', array['PKU']::text[], 'Genetics')
on conflict (slug) do update set
    canonical_name    = excluded.canonical_name,
    alternative_names = excluded.alternative_names,
    category          = excluded.category,
    updated_at        = now();

insert into public.diagnoses (slug, canonical_name, alternative_names, category) values
    ('maple-syrup-urine-disease', 'Maple Syrup Urine Disease', array['MSUD']::text[], 'Genetics'),
    ('fragile-x-syndrome', 'Fragile X Syndrome', '{}'::text[], 'Genetics'),
    ('prader-willi-syndrome', 'Prader-Willi Syndrome', array['PWS']::text[], 'Genetics'),
    ('angelman-syndrome', 'Angelman Syndrome', '{}'::text[], 'Genetics'),
    ('achondroplasia', 'Achondroplasia', '{}'::text[], 'Genetics'),
    ('marfan-syndrome', 'Marfan Syndrome', '{}'::text[], 'Genetics'),
    ('ehlers-danlos-syndrome', 'Ehlers-Danlos Syndrome', array['EDS']::text[], 'Genetics'),
    ('osteogenesis-imperfecta', 'Osteogenesis Imperfecta', array['OI', 'Brittle Bone Disease']::text[], 'Genetics'),
    ('duchenne-muscular-dystrophy', 'Duchenne Muscular Dystrophy', array['DMD']::text[], 'Genetics'),
    ('becker-muscular-dystrophy', 'Becker Muscular Dystrophy', array['BMD']::text[], 'Genetics'),
    ('myotonic-dystrophy', 'Myotonic Dystrophy', array['DM1', 'Steinert Disease']::text[], 'Genetics'),
    ('von-hippel-lindau', 'Von Hippel-Lindau Disease', array['VHL', 'Von Hippel Lindau Disease']::text[], 'Genetics'),
    ('ovarian-cancer', 'Ovarian Cancer', '{}'::text[], 'Oncology'),
    ('cin', 'Cervical Intraepithelial Neoplasia', array['CIN']::text[], 'Oncology'),
    ('cervical-cancer', 'Invasive Cervical Cancer', array['Cervical Cancer']::text[], 'Oncology'),
    ('breast-cancer', 'Breast Cancer', '{}'::text[], 'Oncology')
on conflict (slug) do update set
    canonical_name    = excluded.canonical_name,
    alternative_names = excluded.alternative_names,
    category          = excluded.category,
    updated_at        = now();
