-- Rounds — verify the content import. Run LAST. Nothing here writes.
--
-- The row counts are the easy part. `orphaned_history_case_ids` is the one
-- that matters.
--
-- Case ids are not generated by the database. They are computed from the
-- diagnosis name — sha256('rounds.case.' || lower(trim(diagnosis))), first 16
-- bytes used raw as a UUID — and reproduced in Python by the exporter. Every
-- CaseHistoryEntry ever written by a real device points at one of those ids.
--
-- So public.case_history, which was populated by actual phones with no
-- involvement from the exporter, is an independent check on whether that
-- reproduction is byte-for-byte correct. If a single history row references a
-- case id the imported library doesn't contain, the derivation is wrong and
-- the import must not be trusted: every student's history would detach from
-- the cases it points at.
--
-- orphaned_history_case_ids MUST be 0.

select
    (select count(*) from public.cases)                     as cases,
    (select count(*) from public.diagnoses)                 as diagnoses,
    (select count(*) from public.daily_cases)               as scheduled_days,
    (select count(distinct case_id) from public.case_history) as history_case_ids,
    (select count(*) from (
        select distinct h.case_id
          from public.case_history h
         where not exists (select 1 from public.cases c where c.id = h.case_id)
     ) x)                                                   as orphaned_history_case_ids,
    (select c.diagnosis
       from public.daily_cases d
       join public.cases c on c.id = d.case_id
      where d.day = current_date)                           as todays_daily_case,
    (select count(*) from public.cases where diagnosis_slug is null)      as cases_without_slug,
    (select count(*) from public.cases c
      where c.diagnosis_slug is null
        and cardinality(c.alternative_names) = 0
        and not exists (
            select 1 from public.diagnoses d
             where lower(btrim(d.canonical_name)) = lower(btrim(c.diagnosis))
        ))                                                  as cases_matching_exact_name_only;
