//
//  ConnectionsData.swift
//  Rounds
//
//  Case Connections puzzle data.
//  Adapted from "Clerkship Connections" by Michael Yao (MIT License),
//  used with the author's permission.
//

import Foundation

/// One group in a Connections puzzle: a clinical concept and its four elements.
nonisolated struct ConnectionGroup: Identifiable, Hashable, Sendable {
    let id = UUID()
    let specialties: [String]
    let concept: String
    let elements: [String]
}

nonisolated enum ConnectionsData {
    static let groups: [ConnectionGroup] = [
        ConnectionGroup(specialties: ["emergency medicine", "internal medicine"], concept: "STEMI management", elements: ["Nitroglycerin", "PCI", "Tenecteplase", "DAPT"]),
        ConnectionGroup(specialties: ["emergency medicine"], concept: "Pulseless VT ACLS meds", elements: ["Vasopressin 40 U", "Epinephrine 1 mg IV", "Amiodarone 300 mg", "Lidocaine 1 mg/kg"]),
        ConnectionGroup(specialties: ["emergency medicine", "internal medicine"], concept: "Hypertensive emergency meds", elements: ["Nicardipine", "Nitroprusside", "Labetalol", "Clevidipine"]),
        ConnectionGroup(specialties: ["emergency medicine", "neurology"], concept: "Contraindications to tPA", elements: ["Prior ICH", "Prior stroke within past 3 months", "Active bleeding", "Intracranial neoplasm"]),
        ConnectionGroup(specialties: ["emergency medicine", "internal medicine"], concept: "Status asthmaticus meds", elements: ["Albuterol", "Iptratropium", "Methylprednisolone", "Magnesium sulfate"]),
        ConnectionGroup(specialties: ["emergency medicine", "pediatrics"], concept: "Epiglottitis", elements: ["Dysphagia", "Hot potato voice", "Drooling", "Tripod positioning"]),
        ConnectionGroup(specialties: ["emergency medicine"], concept: "Acetaminophen overdose treatment", elements: ["Liver transplant", "Rumack-Matthew nomogram", "N-acetylcysteine", "Activated charcoal"]),
        ConnectionGroup(specialties: ["emergency medicine"], concept: "Organophosphate poisoning management", elements: ["Decontamination", "Hemodialysis", "Atropine", "Pralidoxime"]),
        ConnectionGroup(specialties: ["emergency medicine", "internal medicine"], concept: "Serotonin syndrome", elements: ["MAOIs", "Linezolid", "Tramadol", "Sumatriptan"]),
        ConnectionGroup(specialties: ["internal medicine"], concept: "Tumor lysis syndrome", elements: ["Hyperuricemia", "Cairo-Bishop criteria", "Hyperphosphatemia", "Hypocalcemia"]),
        ConnectionGroup(specialties: ["emergency medicine"], concept: "Acute angle-closure glaucoma treatment", elements: ["Timolol", "Pilocarpine", "Acetazolamide", "Laser iridotomy"]),
        ConnectionGroup(specialties: ["pediatrics"], concept: "Pediatric GI findings", elements: ["Target sign on US", "Olive shaped mass", "Whirlpool sign", "Double bubble"]),
        ConnectionGroup(specialties: ["pediatrics", "emergency medicine"], concept: "Croup", elements: ["Parainfluenza", "Steeple sign", "Nebulized racemic epi", "Barking cough"]),
        ConnectionGroup(specialties: ["pediatrics", "emergency medicine"], concept: "Signs of nonaccidental trauma", elements: ["Bilateral retinal hemorrhages", "Metaphyseal corner fractures", "Posterior rib fractures", "Unexplained bruising"]),
        ConnectionGroup(specialties: ["emergency medicine", "surgery"], concept: "Components of MTP", elements: ["pRBC", "FFP", "Platelets", "Calcium gluconate"]),
        ConnectionGroup(specialties: ["internal medicine", "psychiatry"], concept: "Alcohol withdrawal stages", elements: ["Tremors and diaphoresis", "Hallucinosis", "Generalized seizures", "Delirium tremens"]),
        ConnectionGroup(specialties: ["internal medicine", "emergency medicine"], concept: "Diabetic ketoacidosis", elements: ["Kussmaul breathing", "Fruity breath", "Polyuria", "Hyperglycemia"]),
        ConnectionGroup(specialties: ["internal medicine", "emergency medicine"], concept: "Anion gap metabolic acidosis causes", elements: ["Lactic acidosis", "Iron overdose", "Ethylene glycol", "Uremia"]),
        ConnectionGroup(specialties: ["internal medicine"], concept: "DIC lab findings", elements: ["Thrombocytopenia", "Low fibrinogen", "Elevated D-dimer", "Coagulopathy"]),
        ConnectionGroup(specialties: ["internal medicine", "emergency medicine"], concept: "ARDS Berlin criteria", elements: ["Acute onset", "Bilateral CXR infiltrates", "PaO2/FiO2 < 300 mmHg", "Not explained by cardiac problem"]),
        ConnectionGroup(specialties: ["internal medicine", "emergency medicine"], concept: "Acute right heart failure findings", elements: ["New RBBB", "S1Q3T3 on EKG", "McConnell's sign", "Elevated JVP"]),
        ConnectionGroup(specialties: ["internal medicine", "family medicine"], concept: "Secondary causes of HTN", elements: ["OSA", "Primary aldosteronism", "Pheochromocytoma", "Recreational drug use"]),
        ConnectionGroup(specialties: ["internal medicine", "family medicine"], concept: "Lipid lowering meds", elements: ["Rosuvastatin", "Ezetimibe", "PCSK9 inhibitors", "Niacin"]),
        ConnectionGroup(specialties: ["internal medicine", "family medicine"], concept: "Diabetes mellitus management", elements: ["Eye exam", "Foot exam", "HbA1c", "Lipid panel"]),
        ConnectionGroup(specialties: ["internal medicine"], concept: "Hyperthyroidism treatment", elements: ["Propranolol", "Methimazole", "Propylthiouracil", "Radioactive iodine"]),
        ConnectionGroup(specialties: ["internal medicine", "family medicine"], concept: "Indications for pneumococcal vaccine", elements: ["Asplenia", "HIV", "Hodgkin lymphoma", "Nephrotic syndrome"]),
        ConnectionGroup(specialties: ["internal medicine", "family medicine"], concept: "Gout triggers", elements: ["Shellfish", "Alcohol", "Red meat", "High fructose corn syrup"]),
        ConnectionGroup(specialties: ["internal medicine", "family medicine"], concept: "COPD meds", elements: ["Tiotropium", "Home O2 therapy", "Salmeterol", "Budesonide"]),
        ConnectionGroup(specialties: ["psychiatry", "pediatrics", "family medicine"], concept: "ADHD meds", elements: ["Atomoxetine", "Guanfacine", "Clonidine", "Concerta or Vyvanse"]),
        ConnectionGroup(specialties: ["family medicine", "internal medicine"], concept: "Smoking cessation management", elements: ["Nicotine patch", "Varenicline", "Bupropion", "Cessation program referral"]),
        ConnectionGroup(specialties: ["psychiatry", "internal medicine", "family medicine"], concept: "Alcohol use disorder management", elements: ["CAGE questionnaire", "CIWA Score", "Motivational interviewing", "Acamprosate"]),
        ConnectionGroup(specialties: ["pediatrics", "family medicine"], concept: "Acute otitis pathogens", elements: ["Strep pneumo", "H influenzae", "Moraxella catarrhalis", "Pseudomonas"]),
        ConnectionGroup(specialties: ["family medicine", "internal medicine"], concept: "Low back pain red flag symptoms", elements: ["Bowel dysfunction", "Urinary incontinence", "Saddle anesthesia", "Pain at night"]),
        ConnectionGroup(specialties: ["family medicine"], concept: "Acne vulgaris treamtn", elements: ["Topical retinoid", "Oral doxycycline", "Hormonal therapy", "Oral isotretinoin"]),
        ConnectionGroup(specialties: ["pediatrics", "family medicine"], concept: "Enuresis treatment", elements: ["Bed-wetting alarm", "Nocturnal fluid restriction", "Desmopressin", "Imipramine"]),
        ConnectionGroup(specialties: ["internal medicine"], concept: "HFrEF GDMT", elements: ["Entresto", "Metoprolol", "Jardiance", "Spironolactone"]),
        ConnectionGroup(specialties: ["internal medicine"], concept: "Vitamin A deficiency", elements: ["Bitot spots", "Night blindness", "Follicular hyperkeratosis", "Xerophthalmia"]),
        ConnectionGroup(specialties: ["internal medicine"], concept: "Vitamin B12 deficiency causes", elements: ["Anti-intrinsic factor Ab", "Chronic PPI use", "Gastric bypass", "Metformin"]),
        ConnectionGroup(specialties: ["internal medicine"], concept: "Folate deficiency causes", elements: ["Sulfasalazine", "Trimethoprim", "Phenytoin", "Methotrexate"]),
        ConnectionGroup(specialties: ["internal medicine"], concept: "Pellagra (B3 deficiency)", elements: ["Dementia", "Diarrhea", "Casal necklace", "Photosensitive dematitis"]),
        ConnectionGroup(specialties: ["internal medicine", "family medicine"], concept: "Iron deficiency anemia", elements: ["Low TIBC", "High RDW", "Low ferritin", "Low MCV"]),
        ConnectionGroup(specialties: ["internal medicine"], concept: "Barrett's esophagus risk factors", elements: ["Chronic GERD", "Male sex", "Obesity", "Cigarette smoking"]),
        ConnectionGroup(specialties: ["internal medicine", "family medicine"], concept: "Hypothyroidism symptoms", elements: ["Fatigue", "Weight gain", "Cold intolerance", "Constipation"]),
        ConnectionGroup(specialties: ["internal medicine", "family medicine"], concept: "Hyperthyroidism symptoms", elements: ["Palpitations", "Weight loss", "Heat intolerance", "Resting tremor"]),
        ConnectionGroup(specialties: ["internal medicine", "family medicine"], concept: "Osteoporosis risk factors", elements: ["Post menopause", "Chronic steroid use", "Low calcium", "Low vitamin D"]),
        ConnectionGroup(specialties: ["internal medicine", "family medicine"], concept: "ACE inhibitors", elements: ["Lisinopril", "Enalapril", "Captopril", "Ramipril"]),
        ConnectionGroup(specialties: ["internal medicine"], concept: "QTc prolonging drugs", elements: ["Amiodarone", "Haloperidol", "Methadone", "Azithromycin"]),
        ConnectionGroup(specialties: ["internal medicine"], concept: "Drug-Induced Lupus causes", elements: ["Hydralazine", "Procainamide", "Isoniazid", "Minocycline"]),
        ConnectionGroup(specialties: ["internal medicine"], concept: "Cushing's syndrome findings", elements: ["Moon facies", "Central obesity", "Purple striae", "Proximal muscle weakness"]),
        ConnectionGroup(specialties: ["internal medicine"], concept: "RIPE treatment for active Tuberculosis", elements: ["Rifampin", "Isoniazid", "Pyrazinamide", "Ethambutol"]),
        ConnectionGroup(specialties: ["internal medicine", "family medicine"], concept: "Microvascular Complications of Diabetes Mellitus", elements: ["Retinopathy", "Nephropathy", "Peripheral neuropathy", "Autonomic neuropathy"]),
        ConnectionGroup(specialties: ["internal medicine", "family medicine"], concept: "CYP450 inducers", elements: ["Rifampin", "Phenytoin", "Carbamazepine", "St. John's wort"]),
        ConnectionGroup(specialties: ["internal medicine", "family medicine"], concept: "CYP450 inhibitors", elements: ["Fluconazole", "Erythromycin", "Amiodarone", "Cimetidine"]),
        ConnectionGroup(specialties: ["internal medicine"], concept: "Hemolytic anemia findings", elements: ["Elevated LDH", "Elevated indirect bilirubin", "Low haptoglobin", "Reticulocytosis"]),
        ConnectionGroup(specialties: ["internal medicine"], concept: "Hypercalcemia causes", elements: ["Hyperparathyroidism", "Malignancy", "Sarcoidosis", "Vitamin D toxicity"]),
        ConnectionGroup(specialties: ["internal medicine", "pediatrics"], concept: "Major Complications of Sickle Cell Disease", elements: ["Vaso-occlusive episodes", "Acute chest syndrome", "Ischemic stroke", "Splenic sequestration"]),
        ConnectionGroup(specialties: ["internal medicine"], concept: "Drugs that cause gynecomastia", elements: ["Spironolactone", "Cimetidine", "Ketoconazole", "Digoxin"]),
        ConnectionGroup(specialties: ["internal medicine"], concept: "Drugs associated with agranulocytosis", elements: ["Clozapine", "Methimazole", "Carbamazepine", "Propylthiouracil"]),
        ConnectionGroup(specialties: ["internal medicine"], concept: "Multiple myeloma findings", elements: ["Hypercalcemia", "Renal insufficiency", "Anemia", "Lytic bone lesions"]),
        ConnectionGroup(specialties: ["internal medicine"], concept: "Seronegative arthropathies", elements: ["Ankylosing spondylitis", "Reactive arthritis", "Psoriatic arthritis", "IBD-associated arthropathy"]),
        ConnectionGroup(specialties: ["internal medicine"], concept: "Wilson's disease findings", elements: ["Kayser-Fleischer rings", "Liver disease", "Tremors and psychosis", "Low serum ceruloplasmin"]),
        ConnectionGroup(specialties: ["internal medicine", "family medicine"], concept: "Community-acquired pneumonia organisms", elements: ["Streptococcus pneumoniae", "Mycoplasma pneumoniae", "Haemophilus influenzae", "Legionella pneumophila"]),
        ConnectionGroup(specialties: ["internal medicine"], concept: "Loop diuretics", elements: ["Furosemide", "Bumetanide", "Torsemide", "Ethacrynic acid"]),
        ConnectionGroup(specialties: ["internal medicine"], concept: "Aminoglycosides", elements: ["Gentamicin", "Tobramycin", "Amikacin", "Streptomycin"]),
        ConnectionGroup(specialties: ["internal medicine"], concept: "Peptic ulcer disease risk factors", elements: ["H. pylori infection", "NSAID or aspirin use", "Cigarette smoking", "Zollinger-Ellison syndrome"]),
        ConnectionGroup(specialties: ["internal medicine", "surgery"], concept: "Painless jaundice causes", elements: ["Pancreatic head adenocarcinoma", "Cholangiocarcinoma", "Primary sclerosing cholangitis", "Ampullary carcinoma"]),
        ConnectionGroup(specialties: ["internal medicine", "neurology"], concept: "Peripheral neuropathy causes", elements: ["Isoniazid", "Metronidazole", "Vincristine", "Paclitaxel"]),
        ConnectionGroup(specialties: ["internal medicine"], concept: "Chronic lymphocytic leukemia", elements: ["Smudge cells", "Lymphadenopathy", "Indolent presentation", "Autoimmune hemolysis"]),
        ConnectionGroup(specialties: ["internal medicine", "emergency medicine"], concept: "AFib with RVR management", elements: ["Metoprolol", "Diltiazem", "Amiodarone", "Cardioversion"]),
        ConnectionGroup(specialties: ["internal medicine"], concept: "Types of AV block", elements: ["P-QRS dissociation", "Fixed PR, random QRS drop", "Progressive PR prolongation", "Constant PR prolongation"]),
        ConnectionGroup(specialties: ["internal medicine", "emergency medicine"], concept: "Post-MI complications", elements: ["Papillary muscle rupture", "Free wall rupture", "Dressler syndrome", "LV aneurysm"]),
        ConnectionGroup(specialties: ["internal medicine", "emergency medicine"], concept: "Cardiac tamponade exam", elements: ["Beck's triad", "Pulsus paradoxus", "RV diastolic collapse", "Distant heart sounds"]),
        ConnectionGroup(specialties: ["internal medicine"], concept: "Infective endocarditis", elements: ["Duke criteria", "Janeway lesions", "Osler nodes", "Roth spots"]),
        ConnectionGroup(specialties: ["surgery", "internal medicine"], concept: "Leriche syndrome", elements: ["Aortoiliac occlusion", "Bilateral claudication", "Absent femoral pulses", "Erectile dysfunction"]),
        ConnectionGroup(specialties: ["emergency medicine"], concept: "Types of shock", elements: ["Anaphylaxis", "Massive internal bleeding", "Saddle PE", "Neurogenic"]),
        ConnectionGroup(specialties: ["internal medicine"], concept: "Nasopharyngeal carcinoma", elements: ["EBV association", "Immigrant from Southern China", "Nasal obstruction", "Unilateral otitis media"]),
        ConnectionGroup(specialties: ["internal medicine"], concept: "Causes of drug-induced liver injury", elements: ["Isoniazid", "Statins", "Augmentin", "Bactrim"]),
        ConnectionGroup(specialties: ["internal medicine"], concept: "Alcoholic hepatitis", elements: ["AST:ALT ratio > 2", "Elevated alk phos and GGT", "Maddrey's discriminant function", "Treat with abstinence"]),
        ConnectionGroup(specialties: ["internal medicine"], concept: "Possible cirrhosis meds", elements: ["Furosemide", "Spironolactone", "Lactulose", "Rifaximin"]),
        ConnectionGroup(specialties: ["internal medicine", "surgery"], concept: "Focal nodular hyperplasia", elements: ["Central stellate scar", "Not OCP-related", "No malignant potential", "Spoke-wheel pattern"]),
        ConnectionGroup(specialties: ["internal medicine"], concept: "Primary sclerosing cholangitis", elements: ["Beads on string", "Associated with UC", "p-ANCA positive", "Treat with liver transplant"]),
        ConnectionGroup(specialties: ["internal medicine", "surgery", "emergency medicine"], concept: "Pancreatitis", elements: ["Hypertriglyceridemia", "Pancreatic calcifications", "Balthazar score", "Low fecal elastase"]),
        ConnectionGroup(specialties: ["internal medicine"], concept: "Paroxysmal nocturnal hemoglobinuria (PNH)", elements: ["PIGA mutation", "Intravascular hemolysis", "Absent CD55/CD59", "Treatment with eculizumab"]),
        ConnectionGroup(specialties: ["internal medicine"], concept: "Causes of thrombocytopenia", elements: ["Antiplatelet IgG Ab", "ADAMTS13 deficiency", "PF4-heparin antibodies", "Consumption of clotting factors and platelets"]),
        ConnectionGroup(specialties: ["internal medicine"], concept: "APLS antibodies", elements: ["Lupus anticoagulant", "Anti-cardiolipin", "Anti-beta2 glycoprotein", "ANA"]),
        ConnectionGroup(specialties: ["internal medicine", "surgery"], concept: "DVT prophylaxis inpatient", elements: ["Heparin", "Lovenox", "Fondaparinux", "Bivalirudin"]),
        ConnectionGroup(specialties: ["internal medicine"], concept: "Causes of severe ESR elevation", elements: ["Infection", "Malignancy", "Polymyalgia rheumatica", "Giant cell arteritis"]),
        ConnectionGroup(specialties: ["internal medicine"], concept: "Tumor lysis syndrome", elements: ["Hyperuricemia", "Hyperphosphatemia", "Hyperkalemia", "Hyper-LDH"]),
        ConnectionGroup(specialties: ["internal medicine"], concept: "Transfusion reactions", elements: ["Febrile non-hemolytic", "AHTR", "TRALI", "Delayed hemolytic"]),
        ConnectionGroup(specialties: ["internal medicine"], concept: "Polyarteritis nodosa", elements: ["Medium-vessel necrotizing vasculitis", "Hepatitis B association", "String of pearls on angiography", "Mononeuritis multiplex"]),
        ConnectionGroup(specialties: ["internal medicine"], concept: "Opportunistic HIV infections (CD4 < 100)", elements: ["HHV-8", "JC virus", "Cryptococcus neoformans", "Mycobacterium avium complex"]),
        ConnectionGroup(specialties: ["internal medicine"], concept: "Chagas disease", elements: ["Trypanosoma cruzi", "Romana's sign", "Cardiomyopathy", "Megaesophagus"]),
        ConnectionGroup(specialties: ["internal medicine"], concept: "DRESS syndrome causes", elements: ["Bactrim", "Allopurinol", "Carbamezapine", "Lamotrigene"]),
        ConnectionGroup(specialties: ["internal medicine", "family medicine"], concept: "Infections requiring treatment of contacts", elements: ["Neisseria meningitidis", "Pertussis", "Scabies", "Trichomonas vaginalis"]),
        ConnectionGroup(specialties: ["neurology", "emergency medicine"], concept: "Contraindications to tPA", elements: ["Presenting 12 hrs after symptom onset", "BP 190/110", "Recent surgery", "Platelets < 100k"]),
        ConnectionGroup(specialties: ["neurology", "emergency medicine"], concept: "Hemorrhagic stroke management", elements: ["Elevate head of bed", "Transexamic acid", "Reverse AC", "Blood pressure management"]),
        ConnectionGroup(specialties: ["neurology", "emergency medicine"], concept: "Subarachnoid hemorrhage", elements: ["Thunderclap headache", "Xanthochromia on LP", "Nimodipine treatment", "Endovascular coiling"]),
        ConnectionGroup(specialties: ["neurology", "emergency medicine"], concept: "Cerebellar hemorrhage", elements: ["Ipsilateral ataxia and nystagmus", "Urgent surgical decompression", "SOC with NSg", "Dysarthria and vertigo"]),
        ConnectionGroup(specialties: ["neurology"], concept: "Lacunar stroke locations", elements: ["Basal ganglia", "Internal capsule", "Corona radiata", "Thalamus"]),
        ConnectionGroup(specialties: ["neurology", "internal medicine"], concept: "Possible stroke treatments", elements: ["Aspirin", "Statin", "DOAC", "BP control"]),
        ConnectionGroup(specialties: ["neurology", "emergency medicine"], concept: "Septic cavernous sinus thrombosis", elements: ["Recent facial infection", "Chemosis and high fever", "Periorbital edema", "CN III and VI palsy"]),
        ConnectionGroup(specialties: ["neurology"], concept: "Normal pressure hydrocephalus", elements: ["Urinary incontinence", "Therapeutic LP", "Wide-based gait", "Cognitive dysfunction"]),
        ConnectionGroup(specialties: ["neurology"], concept: "Alzheimer disease meds", elements: ["Donepezil", "Rivastigmine", "Galantamine", "Memantine"]),
        ConnectionGroup(specialties: ["neurology"], concept: "Dementia with Lewy bodies", elements: ["Fluctuating cognition", "Memory relatively preserved", "Visual hallucinations", "Antipsychotic sensitivity"]),
        ConnectionGroup(specialties: ["neurology"], concept: "Frontotemporal dementia", elements: ["Personality changes", "Executive dysfunction", "Tau or TDP-43 inclusions", "Inappropriate behavior"]),
        ConnectionGroup(specialties: ["neurology"], concept: "Creutzfeldt-Jakob disease", elements: ["Rapidly progressive dementia", "14-3-3 protein in CSF", "Cortical ribboning", "Myoclonus and ataxia"]),
        ConnectionGroup(specialties: ["neurology", "psychiatry"], concept: "Wernicke encephalopathy / Korsakoff syndrome", elements: ["AMS", "Thiamine deficiency", "Ophthalmoplegia", "Ataxic gait"]),
        ConnectionGroup(specialties: ["psychiatry", "neurology"], concept: "Extrapyrimadal side effects", elements: ["Acute dystonia", "Akathisia", "Parkinsonism", "Tardive dyskinesia"]),
        ConnectionGroup(specialties: ["neurology"], concept: "Essential tremor", elements: ["Strong genetic component", "Worsens with intentional movement", "Improves with primidone", "Improves with alcohol"]),
        ConnectionGroup(specialties: ["neurology"], concept: "Huntington disease", elements: ["Chorea", "Caudate nucleus", "Trinucleotide repeat", "Anticipation"]),
        ConnectionGroup(specialties: ["neurology", "psychiatry"], concept: "REM sleep behavior disorder", elements: ["Narcolepsy", "Antidepressant use", "Parkinson disease", "Lewy body dementia"]),
        ConnectionGroup(specialties: ["neurology"], concept: "Narcolepsy", elements: ["Cataplexy", "Low hypocretin levels", "Shortened REM latency", "Treat with modafinil"]),
        ConnectionGroup(specialties: ["neurology", "pediatrics"], concept: "Absence seizure", elements: ["3 Hz spike-and-wave", "Brief staring spells", "Treat with ethosuximide", "Triggered by hyperventilation"]),
        ConnectionGroup(specialties: ["neurology", "pediatrics"], concept: "West syndrome", elements: ["Patient < 1 yo", "Hypsarrhythmia on EEG", "ACTH Treatment", "Vigabitran"]),
        ConnectionGroup(specialties: ["neurology", "family medicine"], concept: "Migraine meds", elements: ["Sumitraptan", "Ubrogepant", "Zolmitriptan", "Ergotamine"]),
        ConnectionGroup(specialties: ["neurology"], concept: "Idiopathic intracranial hypertension", elements: ["Young obese women", "Vitamin A", "Elevated LP opening pressure", "Acetazolamide"]),
        ConnectionGroup(specialties: ["neurology"], concept: "Guillain-Barre syndrome", elements: ["Ascending flaccid paralysis", "Albuminocytologic dissociation", "Campylobacter association", "Treat with IVIG"]),
        ConnectionGroup(specialties: ["neurology", "pediatrics"], concept: "Neurofibromatosis type 1", elements: ["Axillary freckling", "Cafe-au-lait macules", "Lisch nodules", "Annual eye exam"]),
        ConnectionGroup(specialties: ["neurology", "pediatrics"], concept: "Rett syndrome", elements: ["X-linked MECP2 mutation", "Developmental regression", "Breathing irregularities", "Stereotyped hand wringing"]),
        ConnectionGroup(specialties: ["neurology", "pediatrics"], concept: "Tuberous sclerosis", elements: ["Shagreen patches", "Ash-leaf spots", "Cardiac rhabdomyoma", "Renal angiomyolipomas"]),
        ConnectionGroup(specialties: ["neurology", "pediatrics"], concept: "Sturge-Weber syndrome", elements: ["Somatic GNAQ mutation", "Unilateral port-wine stain", "Tram-track calcifications on CT", "Ipsilateral glaucoma"]),
        ConnectionGroup(specialties: ["neurology"], concept: "Meniere disease", elements: ["Unilateral sensorineural hearing loss", "Episodic vertigo", "Tinnitus", "Aural fullness"]),
        ConnectionGroup(specialties: ["neurology"], concept: "Parinaud syndrome", elements: ["Upward gaze palsy", "Collier sign", "Convergence-retraction nystagmus", "Light-near dissociation"]),
        ConnectionGroup(specialties: ["obgyn"], concept: "Normal pregnancy changes", elements: ["Increased GFR", "Dilutional normocytic anemia", "WBC elevated", "Increased protein excretion"]),
        ConnectionGroup(specialties: ["obgyn"], concept: "Quad screen", elements: ["AFP", "Estriol", "Inhibin A", "hCG"]),
        ConnectionGroup(specialties: ["obgyn"], concept: "Gestational diabetes complications", elements: ["Neonatal hypoglycemia", "Fetal macrosomia", "Shoulder dystocia", "Respiratory distress syndrome"]),
        ConnectionGroup(specialties: ["obgyn"], concept: "Pruritis causes during pregnancy", elements: ["PUPPP", "Cholestasis of pregnancy", "Atopic eruption", "Skin stretching"]),
        ConnectionGroup(specialties: ["obgyn", "emergency medicine"], concept: "Causes of painless bleeding during pregnancy", elements: ["Threatened abortion", "Placenta previa", "Vasa previa", "Cervical polyps"]),
        ConnectionGroup(specialties: ["obgyn"], concept: "PPROM exam findings", elements: ["Oligohydramnios on US", "Vaginal pooling of fluid", "Positive nitrazine test", "Positive ferning test"]),
        ConnectionGroup(specialties: ["obgyn"], concept: "Polyhydramnios causes", elements: ["GI atresia", "Maternal diabetes", "Fetal anemia", "Maternal parvovirus"]),
        ConnectionGroup(specialties: ["obgyn"], concept: "Oligohydramnios cases", elements: ["PPROM", "Renal agenesis", "Post-term pregnancy", "IUGR"]),
        ConnectionGroup(specialties: ["obgyn", "internal medicine"], concept: "Extragenital GCCT infections", elements: ["Lymphogranuloma venerum", "Conjuncitivitis", "Pharyngitis", "Purulent tenosynovitis"]),
        ConnectionGroup(specialties: ["internal medicine"], concept: "Manifestations of syphilis", elements: ["Gummas", "Painless chancre", "Hutchinson teeth", "Saber shins"]),
        ConnectionGroup(specialties: ["obgyn"], concept: "US components of BPP", elements: ["Fetal breathing", "Fetal movement", "Fetal tone", "Amniotic fluid"]),
        ConnectionGroup(specialties: ["pediatrics", "obgyn"], concept: "Causes of neonatal hearing loss", elements: ["CMV", "Rubella", "Toxoplasmosis", "HSV"]),
        ConnectionGroup(specialties: ["obgyn", "pediatrics"], concept: "Sequelae of maternal infections", elements: ["High output heart failure", "Intracranial calcifications", "Neonatal cataracts", "Microcephaly"]),
        ConnectionGroup(specialties: ["obgyn", "emergency medicine"], concept: "Causes of postpartum hemorrhage", elements: ["Uterine atony", "Retained products", "Genital tract trauma", "Coagulopathy"]),
        ConnectionGroup(specialties: ["obgyn", "pediatrics"], concept: "Turner syndrome findings", elements: ["Short stature", "Webbed neck", "Wide chest", "Streak ovaries"]),
        ConnectionGroup(specialties: ["surgery", "obgyn"], concept: "Breast masses requiring intervention", elements: ["Phyllodes tumor", "Invasive ductal carcinoma", "Infiltrating lobular carcinoma", "Inflammatory breast carcinoma"]),
        ConnectionGroup(specialties: ["obgyn"], concept: "Secondary causes of amenorrhea", elements: ["Primary ovarian insufficiency", "Turner syndrome", "Kallmann syndrome", "Functional hypothalamic amenorrhea"]),
        ConnectionGroup(specialties: ["obgyn", "family medicine"], concept: "Contraindications to OCPs", elements: ["Prior DVT/PE", "Active smoking in age > 35 yo", "Uncontrolled HTN", "Migraine with aura"]),
        ConnectionGroup(specialties: ["obgyn"], concept: "Risk factors for cervical cancer", elements: ["HPV infection", "Multiple sexual partners", "Immunosupression", "Cigarette smoking"]),
        ConnectionGroup(specialties: ["obgyn"], concept: "Teratogenic medications", elements: ["Isotretinoin", "Depakote", "Warfarin", "Thalidomide"]),
        ConnectionGroup(specialties: ["obgyn", "emergency medicine"], concept: "Risk factors for ectopic pregnancy", elements: ["PID", "Prior ectopic pregnancy", "IUD", "Prior tubal surgery"]),
        ConnectionGroup(specialties: ["pediatrics"], concept: "Neonatal tachypnea etiologies", elements: ["Meconium aspiration", "Respiratory distress syndrome", "Transient tachypnea of the newborn", "Diaphragmatic hernia"]),
        ConnectionGroup(specialties: ["pediatrics"], concept: "Causes of neonatal hyperbili", elements: ["Lactation failure", "Hemolytic disease", "High RBC turnover", "High beta glucuronidase"]),
        ConnectionGroup(specialties: ["obgyn", "pediatrics"], concept: "Complications from delivery", elements: ["Klumpke palsy", "Erb palsy", "Cephalohematoma", "Subgaleal hemorrhage"]),
        ConnectionGroup(specialties: ["pediatrics"], concept: "Manifestations of VACTERL association", elements: ["Tracheo-esophageal fistula", "Anal atresia", "Malformed vertebrae", "Atrial septal defect"]),
        ConnectionGroup(specialties: ["pediatrics"], concept: "Down syndrome complications", elements: ["Hirshsprung disease", "Congenital heart defects", "Duodenal atresia", "Intestinal malrotation"]),
        ConnectionGroup(specialties: ["pediatrics"], concept: "Normal findings in 12 mo", elements: ["Object permanence", "Pulls to stand", "Separation anxiety", "Pincer grasp"]),
        ConnectionGroup(specialties: ["pediatrics", "internal medicine"], concept: "X-linked disorders", elements: ["Bruton's agammaglobulinemia", "Hemophilia A", "Duchenne muscular dystrophy", "Lesch-Nyhan syndrome"]),
        ConnectionGroup(specialties: ["pediatrics"], concept: "PDA-dependent lesions", elements: ["Pulmonary atresia", "Hypoplastic left heart", "Tricuspid atresia", "Transposition of the great vessels"]),
        ConnectionGroup(specialties: ["pediatrics"], concept: "Associated with iron deficiency", elements: ["Breath holding spells", "Lead poisoning", "Microcytic anemia", "Eating ice or dirt"]),
        ConnectionGroup(specialties: ["pediatrics"], concept: "Causes of rectal bleeding", elements: ["Food protein-induced proctocolitis", "Intussusception", "Meckel diverticulum", "Vitamin K deficiency"]),
        ConnectionGroup(specialties: ["pediatrics", "obgyn"], concept: "Sexual development disorders", elements: ["Congenital adrenal hyperplasia", "Androgen insensitivity syndrome", "5-alpha reductase deficiency", "Turner syndrome"]),
        ConnectionGroup(specialties: ["pediatrics", "family medicine"], concept: "NSAID-responsive MSK conditions", elements: ["Transient synovitis of the hip", "Leg-Calve-Perthes disease", "Osteoid osteoma", "Osgood-Schlatter disease"]),
        ConnectionGroup(specialties: ["pediatrics"], concept: "Potter sequence", elements: ["Pulmonary hypoplasia", "Flat facial features", "Low-set ears", "Recessed chin"]),
        ConnectionGroup(specialties: ["pediatrics", "family medicine"], concept: "Vaccines at 2-mo visit", elements: ["DTaP", "Inactivated poliovirus", "H. flu type B", "Pneumococcal (PCV 13)"]),
        ConnectionGroup(specialties: ["pediatrics"], concept: "Causes of neonatal meningitis", elements: ["Group B Strep", "E coli", "Listeria monocytogenes", "Klebsiella pneumoniae"]),
        ConnectionGroup(specialties: ["pediatrics"], concept: "DiGeorge syndrome", elements: ["T-cell deficiency", "Hypo-PTH", "Truncus arteriosus", "Cleft palate"]),
        ConnectionGroup(specialties: ["pediatrics"], concept: "Chediak-Higashi syndrome", elements: ["Easy bleeding", "Peripheral neuropathy", "Albinism", "Frequent infections"]),
        ConnectionGroup(specialties: ["psychiatry"], concept: "Symptoms of manic episode", elements: ["Decreased need for sleep", "Grandiosity", "Pressured speech", "Impulsive behavior"]),
        ConnectionGroup(specialties: ["psychiatry", "family medicine"], concept: "SSRIs", elements: ["Fluoxetine", "Sertraline", "Escitalopram", "Paroxetine"]),
        ConnectionGroup(specialties: ["psychiatry"], concept: "BPD mood stabilizeers", elements: ["Lithium", "Depakote", "Lamotrigene", "Quetiapine"]),
        ConnectionGroup(specialties: ["psychiatry", "emergency medicine"], concept: "Indications for benzos", elements: ["Alcohol withdrawal", "Catatonia", "Seizures", "Delium tremens"]),
        ConnectionGroup(specialties: ["psychiatry", "family medicine"], concept: "Major depressive disorder", elements: ["Decreased REM sleep latency", "Hyperactive HPA axis", "Elevated cortisol levels", "SIGECAPS"]),
        ConnectionGroup(specialties: ["psychiatry", "internal medicine"], concept: "Lithium toxicity", elements: ["New-onset tremor", "Hypothyroidism", "Diabetes insipidus", "Fasciculations"]),
        ConnectionGroup(specialties: ["psychiatry"], concept: "Depakote side effects", elements: ["Thrombocytopenia", "Elevated LFTs", "Pancreatitis", "Neural tube defects"]),
        ConnectionGroup(specialties: ["psychiatry"], concept: "Protective factors against suicide", elements: ["Religious belief", "Social support", "Children at home", "Sense of belonging"]),
        ConnectionGroup(specialties: ["psychiatry"], concept: "ECT indications", elements: ["SI with imminent risk", "Severe psychosis", "Medication resistant MDD", "Catatonia with anorexia"]),
        ConnectionGroup(specialties: ["surgery", "emergency medicine"], concept: "Appendicitis", elements: ["McBurney point tenderness", "Rovsing sign", "CT A/P", "Obturator sign"]),
        ConnectionGroup(specialties: ["surgery"], concept: "SBO", elements: ["High-pitched bowel sounds", "Intestinal adhesions", "Air-fluid levels", "NG tube decompression"]),
        ConnectionGroup(specialties: ["surgery"], concept: "Sigmoid volvulus", elements: ["Neurologically impaired patients", "Coffee-bean sign on CXR", "Sigmoidoscopy", "High recurrence rate"]),
        ConnectionGroup(specialties: ["surgery"], concept: "Cecal volvulus", elements: ["Younger adult patients", "Whirl sign", "Ectopic cecum", "Right hemicolectomy"]),
        ConnectionGroup(specialties: ["surgery"], concept: "Ogilvie syndrome", elements: ["No anatomic obstruction", "Cecal dilitation", "IV neostigmine", "Colonoscopic decompression"]),
        ConnectionGroup(specialties: ["surgery", "emergency medicine"], concept: "Diverticulitis", elements: ["LLQ pain", "CT A/P with contrast", "IV antibiotics +/- drainage", "Colovesical fistula complication"]),
        ConnectionGroup(specialties: ["surgery", "emergency medicine"], concept: "Acute cholecystitis", elements: ["Murphy sign", "Gallbladder wall thickening", "Lap chole", "Post-op bile duct injury"]),
        ConnectionGroup(specialties: ["surgery"], concept: "Internal hemorrhoids", elements: ["Painless rectal bleeding", "Above the dentate line", "Sitz baths", "Stool softeners"]),
        ConnectionGroup(specialties: ["surgery"], concept: "Anal abscess", elements: ["Perianal fluctuance", "Enteric gram-negatives", "Incision and drainage", "Fistula-in-ano complication"]),
        ConnectionGroup(specialties: ["surgery"], concept: "Anal cancer", elements: ["HPV association", "HIV association", "Squamous cell carcinoma", "Nigro protocol"]),
        ConnectionGroup(specialties: ["surgery"], concept: "Colonic adenocarcinoma (hemicolectomy)", elements: ["Hemicolectomy", "CEA monitoring", "FOLFOX therapy", "Lynch syndrome"]),
        ConnectionGroup(specialties: ["surgery", "internal medicine"], concept: "Hepatic adenoma", elements: ["Long-term OCP use", "Risk of spontaneous rupture", "No central scar", "Surgical resection if >5 cm"]),
        ConnectionGroup(specialties: ["surgery", "internal medicine"], concept: "Pyogenic liver abscess", elements: ["Infected biliary stent or stone", "Rim-enhancing liver lesion with air-fluid level", "CT-guided drainage", "IV metronidazole and ceftriaxone"]),
        ConnectionGroup(specialties: ["surgery"], concept: "Hydatid cyst", elements: ["Echinococcus granulosus", "Eggshell calcifications and daughter cysts", "Infected dogs or sheep", "Pre-surgical albendazole"]),
        ConnectionGroup(specialties: ["surgery", "emergency medicine"], concept: "Rectus sheath hematoma", elements: ["Epigastric vessels disruption", "Carnett sign", "Hyperattenuating mass within rectus sheath", "Conservative management"]),
        ConnectionGroup(specialties: ["surgery", "pediatrics"], concept: "Meckel diverticulum", elements: ["2% of population", "2 feet from ileocecal valve", "2 inches long", "Painless GI bleeding in 2 yo"]),
        ConnectionGroup(specialties: ["surgery"], concept: "Testicular torsion", elements: ["Absent cremasteric reflex", "Absent Doppler flow", "Bell clapper deformity", "Bilateral orchidopexy"]),
        ConnectionGroup(specialties: ["surgery", "emergency medicine"], concept: "Aortic dissection", elements: ["Stanford type A or B", "Chest pain radiating to the back", "CT angio or TEE", "Marfan syndrome"]),
        ConnectionGroup(specialties: ["surgery", "emergency medicine"], concept: "Aortic transection", elements: ["Rapid deceleration injury", "Widened mediastinum", "Left hemothorax", "NG tube deviation"]),
        ConnectionGroup(specialties: ["surgery", "emergency medicine"], concept: "Acute limb ischemia", elements: ["Poikilothermia", "Pallor", "Paralysis", "Pulselessness"]),
        ConnectionGroup(specialties: ["surgery", "neurology"], concept: "Carotid stenosis", elements: ["Carotid endarterectomy", "Duplex ultrasound", "Amaurosis fugax", "Statin therapy"]),
        ConnectionGroup(specialties: ["surgery"], concept: "Peripheral artery disease (revascularization)", elements: ["ABI < 0.9", "Claudication", "Smoking cessation", "Supervised exercise program"]),
        ConnectionGroup(specialties: ["surgery", "internal medicine"], concept: "Chronic venous insufficiency", elements: ["Incompetent venous valves", "Varicose veins", "Leg edema", "Lipodermatosclerosis"]),
        ConnectionGroup(specialties: ["internal medicine", "surgery"], concept: "DVT (IVC filter indications)", elements: ["IVC filter vs DOAC", "D-dimer", "DOAC", "Wells' criteria"]),
        ConnectionGroup(specialties: ["surgery"], concept: "Femoral artery pseudoaneurysm", elements: ["Post cardiac cath", "Systolic bruit", "US-guided thrombin injection", "Doppler US"]),
        ConnectionGroup(specialties: ["surgery", "internal medicine"], concept: "Thromboangiitis obliterans", elements: ["Young male heavy smokers", "Distal limb ischemia", "Small- and medium- vessel vasculitis", "Smoking cessation"]),
        ConnectionGroup(specialties: ["surgery", "emergency medicine"], concept: "Pneumothorax", elements: ["Apical bleb rupture", "Tracheal deviation", "Supplemental O2", "Chest tube placement"]),
        ConnectionGroup(specialties: ["surgery", "emergency medicine"], concept: "Esophageal perforation", elements: ["Subcutaneous emphysema", "Gastrografin esophagram", "Left pleural effusion", "Hydropneumothorax"]),
        ConnectionGroup(specialties: ["surgery", "internal medicine"], concept: "Mesothelioma", elements: ["Chronic asbestos exposure", "Asymmetric pleural thickening", "Shipyard work", "Talc pleurodesis"]),
        ConnectionGroup(specialties: ["surgery"], concept: "Anterior mediastinal masses", elements: ["Thymoma", "Teratoma", "Lymphoma", "Thyroid goiter"]),
        ConnectionGroup(specialties: ["surgery"], concept: "Femoral neck fracture", elements: ["Elderly women with osteoporosis", "Garden classification", "Hemiarthroplasty or ORIF", "Fat embolism syndrome"]),
        ConnectionGroup(specialties: ["surgery", "pediatrics"], concept: "SCFE (surgical pinning)", elements: ["Obese adolescents", "Acute hip pain", "Frog-leg lateral X-ray", "Drehmann sign"]),
        ConnectionGroup(specialties: ["surgery", "family medicine"], concept: "Carpal tunnel", elements: ["Thenar atrophy", "Phalen test", "Tinel tests", "Wrist splinting"]),
        ConnectionGroup(specialties: ["surgery", "internal medicine"], concept: "Prostate cancer", elements: ["PSA", "Gleason score", "Radical prostatectomy", "Radiation therapy"]),
        ConnectionGroup(specialties: ["surgery", "obgyn"], concept: "Intraductal papilloma", elements: ["Unilateral bloody nipple discharge", "Small subareolar mass", "Ductogram or breast MRI", "Microdochectomy"]),
        ConnectionGroup(specialties: ["surgery", "internal medicine"], concept: "MEN 2A and/or 2B", elements: ["Thyroid cancer", "Pheochromocytoma", "Parathyroid hyperplasia", "Mucosal neuromas"]),
        ConnectionGroup(specialties: ["surgery"], concept: "Wound VAC contraindications", elements: ["Malignancy", "Necrotic tissue", "Untreated osteomyelitis", "Exposed organs"]),
        ConnectionGroup(specialties: ["surgery", "internal medicine"], concept: "Ranson's criteria", elements: ["Age > 55 yo", "WBC > 16k", "LDH > 350", "Glucose > 200"]),
        ConnectionGroup(specialties: ["surgery", "emergency medicine"], concept: "Acute peritonitis", elements: ["Rebound tenderness", "Involuntary guarding", "Abdominal rigidity", "Absent bowel sounds"]),
        ConnectionGroup(specialties: ["surgery"], concept: "Causes of SBO", elements: ["Adhesions", "GI malignancy", "Volvulus", "Incarcerated hernias"]),
    ]

    /// All specialties that have at least four groups (enough for a puzzle).
    static var playableSpecialties: [String] {
        let counts = Dictionary(grouping: groups.flatMap { g in g.specialties.map { ($0, g) } }, by: { $0.0 })
        return counts.filter { $0.value.count >= 4 }.keys.sorted()
    }

    static func groups(for specialty: String) -> [ConnectionGroup] {
        groups.filter { $0.specialties.contains(specialty) }
    }
}
